const GAME_WIDTH = 1100;
const GAME_HEIGHT = 800;

// Lower the floor to the bottom of the background
const GROUND_Y = GAME_HEIGHT - 28; // Platform height is 28, so ground sits at very bottom

const PLAYER_WIDTH = 50;
const PLAYER_HEIGHT = 68;
const PLAYER_JUMP_VELOCITY = -14;
const PLAYER_MOVE_SPEED = 5.5;

const COINBOY_WIDTH = 48;
const COINBOY_HEIGHT = 58;
const COINBOY_WALK_SPEED = 2.2;
const COINBOY_ROLL_SPEED = 8.2;
const COINBOY_WALK_ANIM_FPS = 10; // frames/sec
const COINBOY_ROLL_ANIM_FPS = 22; // frames/sec

const COINBOY_ATTACK_INTERVAL_MIN = 1.1; // seconds
const COINBOY_ATTACK_INTERVAL_MAX = 3.2; // seconds

const DOOMSHROOM_WIDTH = 54;
const DOOMSHROOM_HEIGHT = 66;
const DOOMSHROOM_WALK_SPEED = 1.45;
const DOOMSHROOM_WALK_ANIM_FPS = 8; // frames/sec
const DOOMSHROOM_HEAL_ANIM_FPS = 7; // frames/sec
const DOOMSHROOM_HEAL_INTERVAL_MIN = 2.7; // seconds
const DOOMSHROOM_HEAL_INTERVAL_MAX = 5.5; // seconds

const PLATFORM_HEIGHT = 28;

window.constants = {
    GAME_WIDTH,
    GAME_HEIGHT,
    GROUND_Y,
    PLAYER_WIDTH,
    PLAYER_HEIGHT,
    PLAYER_JUMP_VELOCITY,
    PLAYER_MOVE_SPEED,
    COINBOY_WIDTH,
    COINBOY_HEIGHT,
    COINBOY_WALK_SPEED,
    COINBOY_ROLL_SPEED,
    COINBOY_WALK_ANIM_FPS,
    COINBOY_ROLL_ANIM_FPS,
    COINBOY_ATTACK_INTERVAL_MIN,
    COINBOY_ATTACK_INTERVAL_MAX,
    DOOMSHROOM_WIDTH,
    DOOMSHROOM_HEIGHT,
    DOOMSHROOM_WALK_SPEED,
    DOOMSHROOM_WALK_ANIM_FPS,
    DOOMSHROOM_HEAL_ANIM_FPS,
    DOOMSHROOM_HEAL_INTERVAL_MIN,
    DOOMSHROOM_HEAL_INTERVAL_MAX,
    PLATFORM_HEIGHT
};